name: Build IMAGE NG
on: 
  repository_dispatch:
  workflow_dispatch:
    inputs:

env:
  BUILDER_NAME: RuralHunter
  TZ: Asia/Shanghai
  DEBIAN_FRONTEND: noninteractive
  # PROJECT: Amlogic-ce
  # DEVICE: Amlogic-ng
  ARCH: arm
jobs:
  make-image:
    name: Build Image
    runs-on: ubuntu-20.04    
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1